export default {
  isSetLocationDialogOpen: false,
  isUserDialogOpen: false,
  isFlaggedDialogOpen: false,
  isAddListingDialogOpen: false,
  isAddAdminDialogOpen: false,
  isAddSchoolDialogOpen: false,
  isAddEventDialogOpen: false,
  isAddOrganizationDialogOpen: false,
  isConfirmDialogOpen: false,
  isViewListingDialogOpen: false,
  isEventDialogOpen: false,
  flaggedItem: {},
  confirmationAction: {},
}
