export default {
  user: {},
  school: {},
  keen: {},
  schoolID: null,
  schools: [],
  newAdmin: {},
  newSchool: {},
  organizationEvents: [],
  sponsoredListings: [],
  availableCategories: [
    'apparel',
    'books',
    'electronics',
    'furniture',
    'housing',
    'recreation',
    'services',
    'subleases',
  ],
}
