export default {
  user: {},
  school: {},
  keen: {},
  schoolID: null,
  schools: [],
  newAdmin: {},
  newSchool: {
    colorRed: 0,
    colorGreen: 0,
    colorBlue: 0,
  },
  organizationEvents: [],
  sponsoredListings: [],
  availableCategories: [
    'apparel',
    'books',
    'electronics',
    'furniture',
    'housing',
    'recreation',
    'services',
    'subleases',
  ],
}
